In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
abalone = pd.read_csv('data/abalone.csv')

In [3]:
data = np.array(abalone)

In [4]:
nvar = data.shape[1]
datax = data[:,1:nvar-1]
datay = data[:,0]
print(datax)
print(datay)

[[0.455 0.365 0.095 ... 0.2245 0.10099999999999999 0.15]
 [0.35 0.265 0.09 ... 0.0995 0.0485 0.07]
 [0.53 0.42 0.135 ... 0.2565 0.1415 0.21]
 ...
 [0.6 0.475 0.205 ... 0.5255 0.2875 0.308]
 [0.625 0.485 0.15 ... 0.531 0.261 0.29600000000000004]
 [0.71 0.555 0.195 ... 0.9455 0.3765 0.495]]
['M' 'M' 'F' ... 'M' 'F' 'M']


In [5]:
from sklearn.model_selection import train_test_split
trnx, tstx, trny, tsty = train_test_split(datax, datay, test_size=0.3, random_state=500)
print(trnx.shape)
print(tstx.shape)
print(trny.shape)
print(tsty.shape)

(2923, 7)
(1254, 7)
(2923,)
(1254,)


In [6]:
from sklearn import tree
tree_model = tree.DecisionTreeClassifier(max_depth=4, random_state=500)
tree_model.fit(X=trnx, y=trny)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=500,
            splitter='best')

In [7]:
from sklearn.metrics import accuracy_score

tree_pred = tree_model.predict(X=tstx)
accuracy_score(tsty, tree_pred)

Accuracy: 0.52


In [ ]:
tree_model.feature_importances_

In [ ]:
from sklearn.tree import export_graphviz
export_graphviz(tree_model, out_file='tree.dot')

위 dot 파일을 그대로 http://www.webgraphviz.com/ 에 긁어붙이면 시각화 가능